a = int(input(""))
b = int(input(""))
result = a + b
print(a, "+", b, "=", result1)
result1 = a - b
print(a, "-", b, "=", result1)
result2 = a * b
print(a, "*", b, "=", result2)
result3 = a / b
print(a, "/", b, "=", result3)
